### ISSUE TITLE
Unable to access the web-ui

### ISSUE THREAD

**Issue by ghost** [vchinnipilli/kubestriker#27]
Hello @vasantchinnipilli!

I've installed the kubestriker in EKS using the yaml files as documented here: https://www.kubestriker.io/-deploying-kubestriker

I have edited the ingress resource within the web-app.yaml to have a host path so that I can have a domain name to access the UI.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubestriker-ui-ingress
  namespace: kubestriker
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
spec:
  rules:
  - host: kubestriker.eks.sandbox.ap2.<company domain>
    http:
      paths:
      - path: /
        backend:
          serviceName: python-svc
          servicePort: 8080
```

I have a Route53 endpoint for *.eks.sandbox.ap2.<company domain>. I have other deployments like Falco, Kiali etc which I have been accessing in the similar manner.

I have edited the API_URL environment variable in the web-app.yaml with the endpoint of the ELB and also the hostname of kubestriker.eks.sandbox.ap2.<company domain> but I get the following error.

![image](https://user-images.githubusercontent.com/24538941/119747094-53501200-bed5-11eb-86eb-b80751d4b207.png)

and the logs in the kubestriker-python pod is this:

```
[26/May/2021 23:54:11] "GET / HTTP/1.1" 404 2070
Not Found: /
[26/May/2021 23:54:40] "GET / HTTP/1.1" 404 2070
Not Found: /
[26/May/2021 23:55:04] "GET / HTTP/1.1" 404 2070
Not Found: /
[26/May/2021 23:55:05] "GET / HTTP/1.1" 404 2070
Not Found: /
[26/May/2021 23:55:06] "GET / HTTP/1.1" 404 2070
Not Found: /
[26/May/2021 23:56:28] "GET / HTTP/1.1" 404 2070
Not Found: /
[26/May/2021 23:57:59] "GET / HTTP/1.1" 404 2070
Not Found: /
[26/May/2021 23:58:00] "GET / HTTP/1.1" 404 2070
Not Found: /
[26/May/2021 23:58:01] "GET / HTTP/1.1" 404 2070
Not Found: /
[26/May/2021 23:58:03] "GET / HTTP/1.1" 404 2070
Not Found: /
[26/May/2021 23:58:05] "GET / HTTP/1.1" 404 2070
```

Can you please suggest on what should I be doing different?
